### PR TITLE
CL random accepts a float argument that can be below 1, so I think this ...

### PR DESCRIPTION
**Pull request by mgi**
...definition matches better.

### CODE REVIEW

**Comment by agrostis** [comment]
CL `random` returns an integer when called with an integer argument and a float when called with a float argument: `(random 4)` is guaranteed to be either 0, 1, 2 or 3. The corresponding JavaScript expression per your definition, `4 * Math.round()` will almost always return a non-integer. I don't see any good way around this problem. JavaScript simply doesn't differentiate between floats and integers (`Number.isInteger(4.0)` returns true, etc.), which means that we'd have to determine what kind of argument our `random` is called with on the Lisp side. If we want to handle the general case, this would cause us to supply PS with a statically checked type system—hardly a realistic prospect. And since our `random` definition is going to be incorrect anyway, we're forced to choose which part of it we prefer to get right: that it work with fractional numbers, or that it return integers on integer input. IMO, the second case occurs more frequently as JavaScript programs go, so I'd rather stick with our current definition. Any objections?

**Comment by vsedach** [comment]
The definition can check for abs(x) < 1 and return a float for numbers less
than 1.

**Comment by mgi** [comment]
Ok. So here is new patch that do what vsedach proposed: best of both world.

**Comment by agrostis** [comment]
Great, thanks! But could you perhaps also keep the no-args version of `random`? Just for reverse compatibility's sake.

**Comment by mgi** [comment]
done.

**Comment by agrostis** [comment]
Oh, and another problem I regrettably have overlooked is that this macro is going to break on `(random (get-height block))` etc. The `arg` of your definition is a macro variable referring to the syntactic form (the list `(get-height block)` in the example) rather an in-code variable referring to the numeric value. May I propose:

```lisp
(def-js-maths
    ...
    (random (&optional arg)
      (if arg
          (maybe-once-only (arg)
            `(if (< (abs ,arg) 1)
                 (* ,arg (funcall (@ *math random)))
                 (floor (* ,arg (funcall (@ *math random))))))
          '(funcall (@ *math random)))))
```

**Comment by mgi** [comment]
Here is agrostis solution. So I think I can close this issue now.

**Pull request closed without merging**
